# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main", "demo" ]
  pull_request:
    branches: [ "main", "demo" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./Backend
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./Backend
    - name: Copy raw-seeding-data folder
      run: |
        # Ensure the raw-seeding-data folder is copied after the build
        cp -r Backend/raw-seeding-data $GITHUB_WORKSPACE/Backend/Aurum.IntegrationTests/bin/Debug/net8.0/Backend/raw-seeding-data
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./Backend
